version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: fullstack-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./deployments/postgres/init-users.sql:/docker-entrypoint-initdb.d/init-users.sql:ro

  mongo:
    image: mongo:7.0
    container_name: fullstack-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: app
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./deployments/mongo/init-users.js:/docker-entrypoint-initdb.d/init-users.js:ro

  redis:
    image: redis:7-alpine
    container_name: fullstack-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: ./backend
    container_name: fullstack-backend
    environment:
      PORT: 8080
      POSTGRES_DSN: postgres://app:app_password@postgres:5432/app?sslmode=disable
      MONGO_URI: mongodb://root:example@mongo:27017/app?authSource=admin
      REDIS_ADDR: redis:6379
      JWT_SECRET: super-secret-development-key
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://backend:8080/api
    container_name: fullstack-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
  mongodata:
  redisdata:
